name: this is cd workflow
on:
  push:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: uotput github context
        run: |
          echo "workflow has been triggered"