name: just information
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:


jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: uotput github context
        run: |
          echo "workflow has been triggered"