name: awesome workflow for pure pyton

on:
  push:


env:
  NAME: "mohammad"
  FAMILY_NAME: "azimi"


jobs:
  env:
    NAME: "mohammad"
    FAMILY_NAME: "azimi"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project Directory
        env:
          NAME: "mamad"
          FAMILY_NAME: "jozani"
        uses: actions/checkout@v5
      - name: Publish To PIP
        shell: bash
        run: |
          echo  ${{ env.NAME }}
          echo  ${{ env.FAMILY_NAME }}
               
