name: Service Containers Demo
on:
  push:


jobs:
  container-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: check mysql container is up and running??
        shell: bash
        run: |
          mysql --host=127.0.0.1 --user=root --password=123321 --database=mysql
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      database:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123321
