name: this is awesome workflow

on:
  push:


jobs:
  aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2


      - name: just test this aws cred
        shell: pwsh
        run: |
          Install-Module -Name AWS.Tools.EC2 -Force
          Get-EC2Vpc

