name: Service Containers Demo
on:
  push:


jobs:
  container-01:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v5
      - name: sleep for a while
        run: |
          sleep 14;
      - name: check mysql container is up and running??
        shell: bash
        run: |
          mysql --host=database --user=root --password=123321 --database=mysql
      - name: create a database
        run:
          mysql --host=database --user=root --password=123321 --database=mysql --execute 'CREATE DATABASE MAMAD;'
      - name: create a database
        run:
          mysql --host=database --user=root --password=123321 --database=mysql --execute 'SHOW DATABASES;'
    services:
      database:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123321
