name: awesome workflow for pure pyton

on:
  push:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project Directory
        uses: actions/checkout@v5
      - name: Publish To PIP
        shell: python
        run: |
          python script.py
          
          
