name: Vault OIDC Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write     
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 1: Get GitHub OIDC token
      - name: Debug OIDC token
        id: oidc
        run: |
          echo "Fetching OIDC token"
          TOKEN=$(curl -sSL \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/mohammadAzimi-cmd")
          echo "OIDC TOKEN:"
          echo $TOKEN
          GH_JWT=$(echo $TOKEN | jq -r '.value')
          echo "GH_JWT=$GH_JWT" >> $GITHUB_ENV

      # Step 2: Login to Vault using JWT
      - name: Vault login via OIDC
        id: vault-login
        run: |
          LOGIN=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            --data "{\"role\": \"github-action\", \"jwt\": \"$GH_JWT\"}" \
            https://charging-jam-fashion-sharing.trycloudflare.com/v1/auth/jwt/login)
          echo "Vault login response:"
          echo $LOGIN
          VAULT_TOKEN=$(echo $LOGIN | jq -r '.auth.client_token')
          echo "VAULT_TOKEN=$VAULT_TOKEN"
          if [ "$VAULT_TOKEN" == "null" ] || [ -z "$VAULT_TOKEN" ]; then
            echo "Vault login failed! Check role, bound_subject, and bound_audiences"
            exit 1
          fi
          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV
