name: this is awesome workflow


on:
  push:

permissions:
  id-token: write




jobs:
  aws_cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to AWS Using OpenID Connect
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::381492032953:role/github-action-oidc
          aws-region: us-west-2

      - name: get the code
        uses: actions/checkout@v3

      - name: run python script
        run: python script/get_all_region.py

      - name: install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
