name: Production Deployment

on:
  push:

permissions:
  packages: write

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: get the code first
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -  name: Build and push
         uses: docker/build-push-action@v6
         with:
          context: .
          push: true
          tags: ghcr.io/test-github-action-aws:${{ github.sha }}