name: this is ci workflow

on:
  pull_request:
  push:
    branches:
      - "dev-*"
      - "feat/**"
      - "main"

env:
  DATABASE_URI: "127.0.0.1"
  DATABASE_USERNAME: "mohammad"
  DATABAE_PASSWORD: "123321"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get The Code
        uses: actions/checkout@v5

      - name: test env variabable
        run: |
          echo $DATABAE_PASSWORD
          echo ${{env.DATABASE_URI}}
          echo ${{env.DATABASE_USERNAME}}



