name: Service Containers Demo
on:
  push:


jobs:
  container-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
      database:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123321