name: this is awesome workflow


on:
  push:

jobs:
  aws_cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: get the code
        uses: actions/checkout@v3


      - name: run python script
        run: python script.py