name: awesome workflow for pure pyton

on:
  push:

env:
  NAME: "mohammad root"
  FAMILY_NAME: "azimi root"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: "mohammad job"
      FAMILY_NAME: "azimi job"
    steps:
      - name: Clone Project Directory
        env:   # 🥇 step-level env (highest precedence)
          NAME: "mamad step"
          FAMILY_NAME: "jozani step"
        uses: actions/checkout@v5

      - name: Publish To PIP
        shell: bash
        run: |
          echo ${{ env.NAME }}
          echo ${{ env.FAMILY_NAME }}
