name: this is awesome workflow
on:
  push:
    branches:
#      - main
      - dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: my first steps
        run: free -h;lsblk;



      - name: my second command
        run: pvs;vgs;lvs