name: Production Deployment

on:
  push:

permissions:
  packages: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker --version
      - run: hostname
      - run: echo "Hello from self-hosted runner!"
#  build_docker_image:
#    runs-on: ubuntu-latest
#    environment: production
#    steps:
#      - name: get the code first
#        uses: actions/checkout@v4
#
#      - name: Log in to GHCR
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set lowercase owner
#        id: repo
#        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
#
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/${{ steps.repo.outputs.owner_lc }}/test-github-action-aws:${{ github.sha }}
