name: this is ci workflow

on:
  pull_request:
  push:
    branches:
      - "dev-*"
      - "feat/**"
      - "main"

env:
  DATABASE_URI: "127.0.0.1"
  DATABASE_USERNAME: "mohammad"
  DATABAE_PASSWORD: "123321"

jobs:
  test:
    environment:
      name: test
#      url:
    runs-on: ubuntu-latest
    steps:
      - name: Get The Code
        uses: actions/checkout@v5

      - name: test env variabable
        run: |
          echo ${{ secrets.USERNAME }}
          echo ${{ secrets.PASSWORD }}



