name: this is awesome workflow

on:
  push:


permissions:
  id-token: write
  contents: read

jobs:
  aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492032953:role/github-action-oidc
          aws-region: us-west-2

      - name: get the code
        uses: actions/checkout@v3


      - name: just test this aws cred
        run: |
          pip install boto3
          python script.py

