name: Vault OIDC Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Vault using GitHub OIDC
        id: vault-login
        uses: hashicorp/vault-action@v2
        with:
          url: https://fundamentals-workshops-trunk-meat.trycloudflare.com
          method: jwt
          role: github-action

      - name: Read secret
        id: vault-read
        uses: hashicorp/vault-action@v2
        with:
          url: https://fundamentals-workshops-trunk-meat.trycloudflare.com
          token: ${{ steps.vault-login.outputs.token }}
          secrets: |
            - path: secret/data/test
              key: MY_SECRET
              engine_version: 2
              format: dotenv

      - name: Print secret
        run: echo "SECRET = $MY_SECRET"
        env:
          MY_SECRET: ${{ steps.vault-read.outputs.MY_SECRET }}
