name: Production Deployment

on:
  push:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: get the code first
        uses: actions/checkout@v4

#      - name:
