name: this is ci workflow

on:
  pull_request:
  push:
    branches:
      - "dev-*" # all branches except main branch
      - "feat/**"
      - "main"
      -




jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get The Code
        uses: actions/checkout@v5

      - name: check we got the code or not
        run: python script.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
       - name: check we got the code or not
         run: python -v

