name: awesome workflow for pure pyton

on:
  push:


env:
  NAME: "mohammad"
  FAMILY_NAME: "azimi"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project Directory
        uses: actions/checkout@v5
      - name: Publish To PIP
        shell: bash
        run: |
          echo "MY_VAR=hello" >> $GITHUB_ENV
          cat $GITHUB_ENV
          printenv
          
          
