name: awesome workflow for pure pyton

on:
  push:





jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project Directory
        uses: actions/checkout@v5
      - name: Publish To PIP
        shell: bash
        run: |
          ls -ll
          python -V
          python script.py
          cat $GITHUB_ENV
          
          
