name: Production Deployment

on:
  push:

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: running production deployment
        run: echo "running production deployment"